data_dir:
  raw: backend/data/raw_pdfs
  reports: backend/data/reports

model:
  chat_model: gpt-4o
  temperature: 0.7

gemini:
  model_name: "gemini-1.5-pro"

deep_seek:
  model_name: "deep-seek-1.0"

llama:
  model_name: "llama-1.0"
  

metadata:
  - filetype
  - page_number
  - filename

image_summarizer:
  model: gpt-4o
  device: cuda
  summaries_dir: backend/data/summaries
  image_summary_dir: backend/data/summaries/image_summaries.json

text_summarizer:
  model: gpt-4o
  text_summary_dir: backend/data/summaries/text_summaries.json

prompts:
  summarizer_prompt_dir: backend/src/prompts/summarizer.json
  prompt_dir: backend/src/prompts
  system_message_prompt: system_message.json
  ror_prompt: rephrase_and_respond.json

vector_database:
  vectorstore_name: test11
  embeddings: OpenAIEmbeddings # if changed need to make change in code
  persist_directory: vb # deprecated
  # image_persist_directory: vector_database/image # added for image 
  # text_persist_directory: vector_database/text # added for text


firebase:
  session_id: user_session_new
  firebase_credentials_path: credentials/firebase_credentials.json
